### ISSUE TITLE
1. Solution exception:unexpected token 'from'

### ISSUE THREAD

**Issue by gerardbertomeu** [AntonelloDN/ShrimpGIS#11]
After installing ShrimpGis, all the components display the following error message:
1. Solution exception:unexpected token 'from'

Any tips? Thanks!

**Comment by gerardbertomeu** [comment]
Please find here a screen capture illustrating the issue:

![Screenshot 2022-09-14 103220](https://user-images.githubusercontent.com/113443466/190103661-4abe3387-8914-46d2-b966-42c59fb211d4.png)

**Comment by grazianoEnzoMarchesani** [comment]
I don't know if there is a correlation, but I have the same problem on one PC where ladybug 1.5 is installed, while on another where ladybug 1.4 is installed, everything works fine

**Comment by gerardbertomeu** [comment]
Thank you! 

I completely uninstall ladybug tools (1.5) and it's back!

**Comment by ncatunda** [comment]
Yep, same here with LBT 1.5. After uninstalling everything works fine :)

PS: It also **does not** work with LBT version **1.6**.

**Comment by grazianoEnzoMarchesani** [comment]
> Yep, same here with LBT 1.5. After uninstalling everything works fine :)
> 
> PS: It also **does not** work with LBT version **1.6**.

No offence to Antonello, who I know and respect so much for his work, but I suggest you try another open source plugin called BearGis

https://github.com/nicoazel/BearGIS

**Comment by JamesParrott** [comment]
Graziano, this issue was not (entirely) Antonello's fault.  ShrimpGIS's dependencies should be structured far better than copying in utm verbatim, including its "use which ever numpy it finds" optional dependency.  

But if you install Lady Bug Tools, and then in a GhPython component simply do `import numpy`, on my machine (Rhino 7) exactly this "unexpected token 'from' " error is reproduced, without shrimpGIS installed, without any other plug-in installed.

![image](https://user-images.githubusercontent.com/80779630/220400968-37ec10a3-ee92-43ba-86cd-c078fae64655.png)

**Comment by grazianoEnzoMarchesani** [comment]
> Graziano, this issue was not (entirely) Antonello's fault. ShrimpGIS's dependencies should be structured far better than copying in utm verbatim, including its "use which ever numpy it finds" optional dependency.
> 
> But if you install Lady Bug Tools, and then in a GhPython component simply do `import numpy`, on my machine (Rhino 7) exactly this "unexpected token 'from' " error is reproduced, without shrimpGIS installed, without any other plug-in installed.
> 
> ![image](https://user-images.githubusercontent.com/80779630/220400968-37ec10a3-ee92-43ba-86cd-c078fae64655.png)

I understand what you mean. Unfortunately I am not able to give an answer.
I hope Antonello can rethink the dependency system in the future because shrimpGis is a plugin I have used a lot and I appreciate Antonello's work very much. Rightly so, he has a lot of other work and the maintenance of this plugin takes a back seat. I also hope that someone will be able to fork the project and maintain it.

**Comment by JamesParrott** [comment]
> I also hope that someone will be able to fork the project and maintain it.

I couldn't agree more!  I think I have fixed this particular dependency conflict with this PR from my own fork a few hours ago:  [https://github.com/AntonelloDN/ShrimpGIS/pull/13](https://github.com/AntonelloDN/ShrimpGIS/pull/13)  (although the potential dependency conflict is still there for any other plug-in to fall into with LadyBug Tools).

But I only deleted a few lines and de-indented a few others (the trick of course, is knowing which lines to delete ;-) ).  And I don't know the shrimpGIS code base well enough and can't commit to maintaining a fork.

**Comment by grazianoEnzoMarchesani** [comment]
> > I also hope that someone will be able to fork the project and maintain it.
> 
> I couldn't agree more! I think I have fixed this particular dependency conflict with this PR from my own fork a few hours ago: #13 (although the potential dependency conflict is still there for any other plug-in to fall into with LadyBug Tools).
> 
> But I only deleted a few lines and de-indented a few others (the trick of course, is knowing which lines to delete ;-) ). And I don't know the shrimpGIS code base well enough and can't commit to maintaining a fork.

I wouldn't be able to either, but thank you very much on behalf of the whole community

**Comment by ncatunda** [comment]
> > Yep, same here with LBT 1.5. After uninstalling everything works fine :)
> > PS: It also **does not** work with LBT version **1.6**.
> 
> No offence to Antonello, who I know and respect so much for his work, but I suggest you try another open source plugin called BearGis
> 
> https://github.com/nicoazel/BearGIS

@grazianoEnzoMarchesani, does BearGIS export z-values? ShrimpGIS is definively a bit more annoying for me to use because I have to deal with different coordinate system, since it only works with WGS84. I always have to transform things back and forth. In that sense BearGIS would be so much more efficient, but not exporting the z-values is a killer criteria to me.

**Comment by JamesParrott** [comment]
I could only find code for treating points as 2D in BearGIS (and couldn't actually get it to export to any shape file at all, without providing attrs, field values and prj).

**Comment by AntonelloDN** [comment]
Solved by #13
